### ISSUE TITLE
Fastify crashes when reply code is not recognized

### ISSUE THREAD

**Issue by chiku** [fastify/help#161]
## 🐛 Bug Report

Fastify crashes when reply code is not recognized.

## To Reproduce

Run fastify server that returns an exotic response code.

```js
const fastify = require('fastify')({ logger: true });

fastify.get('/', async (request, reply) => {
  reply.code(525); // exotic response code
  return { hello: 'world' };
});

const start = async () => {
  try {
    await fastify.listen(3000);
    fastify.log.info(`server listening on ${fastify.server.address().port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
```

Make a request to the server
```bash
curl http://localhost:3000
```

The application crashes.

The HTTP response code is 500 and the response body is as follows.

```json
{"statusCode":500,"code":"FST_ERR_BAD_STATUS_CODE","error":"Internal Server Error","message":"FST_ERR_BAD_STATUS_CODE: Called reply with malformed status code"}
```

## Expected behavior

The application should not crash

## Your Environment

- *node version*: v10.19.0
- *fastify version*: 2.13.0
- *os*: Mac

**Comment by chiku** [comment]
This is the application stack-trace

```
FastifyError [FST_ERR_BAD_STATUS_CODE]: FST_ERR_BAD_STATUS_CODE: Called reply with malformed status code
    at _Reply.Reply.code (node_modules/fastify/lib/reply.js:202:11)
    at Object.fastify.get (index.js:4:9)
    at preHandlerCallback (node_modules/fastify/lib/handleRequest.js:111:30)
    at preValidationCallback (node_modules/fastify/lib/handleRequest.js:100:5)
    at handler (node_modules/fastify/lib/handleRequest.js:69:5)
    at handleRequest (node_modules/fastify/lib/handleRequest.js:18:5)
    at onRunMiddlewares (node_modules/fastify/lib/middleware.js:22:5)
    at middlewareCallback (node_modules/fastify/lib/route.js:381:5)
    at Object.routeHandler [as handler] (node_modules/fastify/lib/route.js:359:7)
    at Router.lookup (node_modules/find-my-way/index.js:349:14)
```

**Comment by chiku** [comment]
I have figured that `code` fails if it is not defined in `node_modules/statuses/codes.json`

**Comment by Eomm** [comment]
Good catch!

To reproduce we need to use this endpoint:

```
fastify.get('/', (request, reply) => {
  reply.code(525).send({ hello: 'world' })
})
```

with `async` handler the server doesn't crash.


In the earlier version 2.12, the code was simply set as the user wanted:

```
curl ...
HTTP/1.1 525 unknown
```

Moving this issue to the main repo as regression

I think we should:

- emit a warning instead of a throw
- throw an error only in v3

cc @mcollina
