### ISSUE TITLE
fastify-express example code error

### ISSUE THREAD

**Issue by hvolmer** [fastify/help#186]
#### You have already researched for similiar issues?
Yes. 

#### What are you trying to achieve or the steps to reproduce?
Run the fastify-express example code at [Add a complete application](https://github.com/fastify/fastify-express#add-a-complete-application). 

#### What was the result you received?
```
C:\working\device-management-api\node_modules\avvio\boot.js:364
  return p.then.bind(p)
           ^

TypeError: Cannot read property 'then' of undefined
    at Boot.thenify (C:\working\device-management-api\node_modules\avvio\boot.js:364:12)   
    at Object._encapsulateThreeParam (C:\working\device-management-api\node_modules\avvio\boot.js:489:13)
    at Boot.timeoutCall (C:\working\device-management-api\node_modules\avvio\boot.js:416:5)    at Boot.callWithCbOrNextTick (C:\working\device-management-api\node_modules\avvio\boot.js:397:19)
    at Boot._after (C:\working\device-management-api\node_modules\avvio\boot.js:266:26)    
    at Plugin.exec (C:\working\device-management-api\node_modules\avvio\plugin.js:129:17)  
    at Boot.loadPlugin (C:\working\device-management-api\node_modules\avvio\plugin.js:261:10)
    at Task.release (C:\working\device-management-api\node_modules\fastq\queue.js:140:16)  
    at worked (C:\working\device-management-api\node_modules\fastq\queue.js:182:10)        
    at C:\working\device-management-api\node_modules\avvio\plugin.js:264:7
```

If I remove `fastify.register(require('fastify-express'))...`, then no error (as expected) but of course there is none of the desired functionality.

#### What did you expect?

A running example

#### Context

* *node version*: 12.16.2
* *fastify version*: >=3.0.0-rc.1
* *fastify-express*: 0.1.0
* *os*: Linux in nodejs docker container

**Comment by Eomm** [comment]
Thanks for reporting, we are checking 👍

**Comment by hvolmer** [comment]
> Thanks for reporting, we are checking 👍

Thank you.  I'm excited to try this as a means of moving my API over in a more-reasonable fashion!

**Comment by Eomm** [comment]
Fixed https://github.com/mcollina/avvio/pull/108

Please reinstall and retry 👍
