### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by Narixius** [fastify/help#244]
#### You have already researched for similar issues?
Yes, but I didn't find anything related to this issue.

#### What are you trying to achieve or the steps to reproduce?

When I started to create a simple app with Fastify version 3.2.0, It gives me some errors. But after downgrading to version 2.15.3, problem solved

```js
// simple hello world index.js

const fastify = require("fastify")({
  logger: true,
});

// Declare a route
fastify.get("/", function (request, reply) {
  reply.send({ hello: "world" });
});

// Run the server!
fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  fastify.log.info(`server listening on ${address}`);
});

```

#### What was the result you received?
The result with version 3.2.1:
```shell
{"level":50,"time":1597419681847,"pid":6792,"hostname":"MY-PC-NAME","generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"==","stack":"AssertionError [ERR_ASSERTION]: Version should be a string
at Router._on ([PATH-TO-PROJECT]\\node_modules\\find-my-way\\index.js:98:5)
at Router.on ([PATH-TO-PROJECT]\\node_modules\\find-my-way\\index.js:73:8)
at Object.afterRouteAdded ([PATH-TO-PROJECT]\\node_modules\\fastify\\lib\\route.js:221:16)
at after ([PATH-TO-PROJECT]\\node_modules\\fastify\\lib\\route.js:167:25
at Object._encapsulateThreeParam ([PATH-TO-PROJECT]\\node_modules\\avvio\\boot.js:545:7)
at Boot.timeoutCall ([PATH-TO-PROJECT]\\node_modules\\avvio\\boot.js:447:5)
at Boot.callWithCbOrNextTick ([PATH-TO-PROJECT]\\node_modules\\avvio\\boot.js:428:19)
at Boot._after ([PATH-TO-PROJECT]\\node_modules\\avvio\\boot.js:273:26)
at Plugin.exec ([PATH-TO-PROJECT]\\node_modules\\avvio\\plugin.js:131:17)
at Boot.loadPlugin ([PATH-TO-PROJECT]\\node_modules\\avvio\\plugin.js:266:10)","type":"Error","msg":"Version should be a string"}
```

#### What did you expect?
Anything but not an error.
#### Context

* *node version*: 10.20.1
* *fastify version*: >=3.2.0
* *os*: Windows
* I start the server using nodemon

**Comment by mcollina** [comment]
This is fixed already, update your dependencies. Sorry for the problem :(
