### ISSUE TITLE
using fastify-swagger and fastify-caching together causes error

### ISSUE THREAD

**Issue by punkish** [fastify/help#259]
With the following Swagger options

```js
options: {
    routePrefix: '/v3/docs',
    exposeRoute: true,
    swagger: { … }
}

app.register(require('fastify-swagger'), swagger.options)
app.register(require('fastify-caching'), { cache: cache })
app.register(require('./api/v3/index'), { prefix: '/v3' })
```

I get an error at `http://…/v3/docs`

```
[1599732238672] INFO  (30066 on lucknow.local): incoming request
    req: {
      "method": "GET",
      "url": "/v3/docs/static/index.html",
      "hostname": "lucknow.local:3010",
      "remoteAddress": "127.0.0.1",
      "remotePort": 57868
    }
    reqId: 3
/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:40
    const p = path.normalize(`${cacheDir}/${key.substr(0, 1)}/${key.substr(0, 2)}/${key.substr(0, 3)}`)
                                                ^

TypeError: key.substr is not a function
    at buildFilePath (/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:40:49)
    at Object.get (/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:164:42)
    at Object.etagHandleRequest (/Users/punkish/Projects/zenrest/node_modules/fastify-caching/plugin.js:35:14)
    at hookIterator (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:221:10)
    at next (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:162:20)
    at hookRunner (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:181:3)
    at Object.routeHandler [as handler] (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/route.js:335:7)
    at Router.lookup (/Users/punkish/Projects/zenrest/node_modules/find-my-way/index.js:356:14)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:790:12)
```

The weird thing is, why is caching being invoked at all? If you follow the stack trace, none of my code is being called until `abstract-cache-file` (which I have written)

If I comment out `fastify-cache` in my code above, I can get to Swagger docs without any problem. What is going on?

**Comment by punkish** [comment]
ok, it seems the error is because of `v3` in both my docs path as well as my api path. If I take out `v3` then it works. Closing this issue

**Comment by punkish** [comment]
well, I spoke too soon. I continue to get the above reported error, and to make matters worse, I can't find a pattern to what causes it. Sometimes I am able to load the Swagger docs, but other times I get an error. Here is one such case

```
[1599744282075] INFO  (37160 on lucknow.local): incoming request
    req: {
      "method": "GET",
      "url": "/docs/static/swagger-ui-bundle.js.map",
      "hostname": "lucknow.local:3010",
      "remoteAddress": "127.0.0.1",
      "remotePort": 49889
    }
    reqId: 11
/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:39
    const p = path.normalize(`${cacheDir}/${key.substr(0, 1)}/${key.substr(0, 2)}/${key.substr(0, 3)}`)
                                                ^

TypeError: key.substr is not a function
    at buildFilePath (/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:39:49)
    at Object.get (/Users/punkish/Projects/zenrest/lib/abstract-cache-file/index.js:163:42)
    at Object.etagHandleRequest (/Users/punkish/Projects/zenrest/node_modules/fastify-caching/plugin.js:35:14)
    at hookIterator (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:221:10)
    at next (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:162:20)
    at hookRunner (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/hooks.js:181:3)
    at Object.routeHandler [as handler] (/Users/punkish/Projects/zenrest/node_modules/fastify/lib/route.js:335:7)
    at Router.lookup (/Users/punkish/Projects/zenrest/node_modules/find-my-way/index.js:356:14)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:790:12)
➜  zenrest 
```

It is absolutely baffling to me why the caching mechanism is being invoked for requests are that not a part of my API

**Comment by punkish** [comment]
> Please provide a minimal reproduction that can be run by `node index.js`.

I will, soon as I can figure out what is causing this error. As I noted, for now, I can't find a way to consistently reproduce it. Sometimes the docs load. Sometimes I get the above error and the app quits

**Comment by punkish** [comment]
I got rid of `fastify-caching` for now so I can move on with my project. When I decide to come back to it, and if I still face the same problem, I will reopen this issue or reopen a new one
