### ISSUE TITLE
Fastify Register throws error

### ISSUE THREAD

**Issue by AsimRamay** [fastify/help#27]
getting an error on npm start when it tries to run server.js it says fastify.register is not a function, and I compared the line with the documentation and can't find anything wrong, the output is as below 

**CMD**
```
03:59:27 fastify.1    |  > node src/server
03:59:28 fastify.1    |  F:\Projects 2018\parkmanager18\src\server.js:3
03:59:28 fastify.1    |  fastify.register(require('fastify-postgres'), {
03:59:28 fastify.1    |          ^
03:59:28 fastify.1    |  TypeError: fastify.register is not a function
03:59:28 fastify.1    |      at Object.<anonymous> (F:\Projects 2018\parkmanager18\src\server.js:3:9)
03:59:28 fastify.1    |      at Module._compile (module.js:653:30)
03:59:28 fastify.1    |      at Object.Module._extensions..js (module.js:664:10)
03:59:28 fastify.1    |      at Module.load (module.js:566:32)
03:59:28 fastify.1    |      at tryModuleLoad (module.js:506:12)
03:59:28 fastify.1    |      at Function.Module._load (module.js:498:3)
03:59:28 fastify.1    |      at Function.Module.runMain (module.js:694:10)
03:59:28 fastify.1    |      at startup (bootstrap_node.js:204:16)
03:59:28 fastify.1    |      at bootstrap_node.js:625:3
```

**Server.js**
```
const fastify = require('fastify')

fastify.register(require('fastify-postgres'), {
    connectionString: 'postgres://postgres@localhost/ParkManager',
    native: true
})

fastify.get('/user/:id', (req, reply) => {
    fastify.pg.query(
        'SELECT * FROM Customers WHERE Customer_ID=$1', [req.params.id],
        function onResult (err, result) {
            reply.send(err || result)
        }
    )
})

fastify.listen(3001, err => {
    if (err) throw err
    console.log(`server listening on ${fastify.server.address().port}`)
})
```

**Comment by mcollina** [comment]
You should replace

```js
const fastify = require('fastify')
```

with

```js
const fastify = require('fastify')()
```
