### ISSUE TITLE
misleading/wrong error message on schema validation

### ISSUE THREAD

**Issue by punkish** [fastify/help#270]
#### You have already researched for similiar issues?
yes

#### What are you trying to achieve or the steps to reproduce?

My aim is to allow in the querystring either `treatmentId` **or** if any param *other than* treatmentId, then require, `$page` and `$size`. After much experimentation, I came up with the following schema that works

```json
{
    "type": "object",
    "properties": {
        "treatmentId": {"type": "string", "maxLength": 32, "minLength": 32},
        "treatmentTitle": {"type": "string"},
        "doi": {"type": "string"},

        … many other params …

        "$page": {"type": "integer", "minimum": 1},
        "$size": {"type": "integer", "minimum": 1, "maximum": 100}
    },
    "anyOf": [
        {
            "not": {
                "properties": {"treatmentId": {"const": ""}},
                "required": []
            }
        },
        {"required": ["$page", "$size"]}
    ]
}
```

#### What was the result you received?
The problem is when I send it an invalid query, the error message is really strange. For example, if I send `treatmentTitle` without the required `$page` and `$size`, the error is

```
err: {
      "type": "Error",
      "message": "querystring should NOT be valid, querystring should have required property '.$page', querystring should match some schema in anyOf",
      "stack":
          Error: querystring should NOT be valid, querystring should have required property '.$page', querystring should match some schema in anyOf
          …
}
```

#### What did you expect?

The message should really say, "querystring is NOT valid, querystring should have required property '.$page', querystring should match some schema in anyOf". That "should NOT be valid" is just the opposite in sense of what is correct.

#### Context

* *node version*: 12.x
* *fastify version*: >=3.4.x
* *os*: Mac

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
Can you please include the full stack from the error? I just want to understand if we allocate this or it is allocated by Ajv.

**Comment by punkish** [comment]
> Can you please include the full stack from the error? I just want to understand if we allocate this or it is allocated by Ajv.

here you go

```
[1601206716117] INFO  (83582 on lucknow): querystring should NOT be valid, querystring should have required property '$page', querystring $size is required, querystring should match some schema in anyOf
    res: {
      "statusCode": 400
    }
    err: {
      "type": "Error",
      "message": "querystring should NOT be valid, querystring should have required property '$page', querystring $size is required, querystring should match some schema in anyOf",
      "stack":
          Error: querystring should NOT be valid, querystring should have required property '$page', querystring $size is required, querystring should match some schema in anyOf
              at defaultSchemaErrorFormatter (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/context.js:53:10)
              at wrapValidationError (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/validation.js:103:15)
              at validate (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/validation.js:89:12)
              at preValidationCallback (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/handleRequest.js:87:16)
              at handler (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/handleRequest.js:70:7)
              at handleRequest (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/handleRequest.js:18:5)
              at runPreParsing (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/route.js:387:5)
              at Object.routeHandler [as handler] (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/route.js:345:7)
              at Router.lookup (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/find-my-way/index.js:356:14)
              at Server.emit (events.js:315:20)
      "validation": [
        {
          "keyword": "not",
          "dataPath": "",
          "schemaPath": "#/anyOf/0/not",
          "params": {},
          "message": "should NOT be valid"
        },
        {
          "keyword": "required",
          "dataPath": "",
          "schemaPath": "#/anyOf/1/required",
          "params": {
            "missingProperty": "$page"
          },
          "message": "should have required property '$page'"
        },
        {
          "keyword": "errorMessage",
          "dataPath": "",
          "schemaPath": "#/anyOf/1/errorMessage",
          "params": {
            "errors": [
              {
                "keyword": "required",
                "dataPath": "",
                "schemaPath": "#/anyOf/1/required",
                "params": {
                  "missingProperty": "$size"
                },
                "message": "should have required property '$size'"
              }
            ]
          },
          "message": "$size is required"
        },
        {
          "keyword": "anyOf",
          "dataPath": "",
          "schemaPath": "#/anyOf",
          "params": {},
          "message": "should match some schema in anyOf"
        }
      ],
      "validationContext": "querystring"
    }
```

**Comment by mcollina** [comment]
The message come from the 'not' keyword in JSON Schema and the Ajv codebase. There is nothing we can do to help with this, as we get those messages from Ajv.
