### ISSUE TITLE
async code inside handler seems to cause handler twice

### ISSUE THREAD

**Issue by punkish** [fastify/help#273]
#### You have already researched for similiar issues?
yes. Reading the following issue led me to the **Promises resolution** part in the docs which say:

```
1. If you want to use async/await or promises but respond a value with reply.send:
Don't return any value.
Don't forget to call reply.send.
```

I am following the above advice but no success

#### What are you trying to achieve or the steps to reproduce?

I have a very simple handler in which I read a local file and send it back

```js
const handler = async function(request, reply) {

    const file = 'path/to/local/file'
    const data = await fsPromises.readFile(file, 'utf8')
    
    if (data.length === 0) {
        throw new Error('No documents found')
    }

    reply.send(data)
}
```

#### What was the result you received?

The strange thing I experience is that the handler seems to be called twice only if I read file asynchronously (as above). This is what the log looks like

```
➜  zenodeo3 git:(master) ✗ node index
[1601343285671] INFO : Server listening at http://127.0.0.1:3010
🏷️  Routes:
GET     /favicon.ico
GET     /docs
GET     /docs/
GET     /docs/json
GET     /docs/yaml
GET     /docs/static/*
GET     /docs/*
GET     /v3/treatments

[1601343285678] INFO : server listening on http://127.0.0.1:3010
[1601343287777] INFO : incoming request
    req: {
      "method": "GET",
      "url": "/v3/treatments?authorityName=starts_with(agosti)",
      "hostname": "127.0.0.1:3010",
      "remoteAddress": "127.0.0.1",
      "remotePort": 60761
    }
    reqId: 1
[1601343287792] INFO : request completed
    res: {
      "statusCode": 200
    }
    responseTime: 13.737338989973068
    reqId: 1
[1601343287793] WARN : Reply already sent
    err: {
      "type": "FastifyError",
      "message": "Reply was already sent.",
      "stack":
          FastifyError: Reply was already sent.
              at _Reply.Reply.send (/Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/reply.js:114:26)
              at /Users/punkish/Projects/zenodeo/zenodeo3/node_modules/fastify/lib/wrapThenable.js:23:15
      "name": "FastifyError",
      "code": "FST_ERR_REP_ALREADY_SENT",
      "statusCode": 500
    }
    reqId: 1
```
#### What did you expect?
I expected that after the first "request complete" step, there would be no further attempt to send a reply.

If I change my code to `fs.readFileSync`, the problem disappears.

```js
const handler = function(request, reply) {
    
    const file = 'path/to/local/file'
    const data = fs.readFileSync(file, 'utf8')
    
    if (data.length === 0) {
        throw new Error('No documents found')
    }
    
    reply.send(data)
}
```

Now the log looks like so

```
➜  zenodeo3 git:(master) ✗ node index
[1601343548398] INFO : Server listening at http://127.0.0.1:3010
🏷️  Routes:
GET     /favicon.ico
GET     /docs
GET     /docs/
GET     /docs/json
GET     /docs/yaml
GET     /docs/static/*
GET     /docs/*
GET     /v3/treatments

[1601343548405] INFO : server listening on http://127.0.0.1:3010
[1601343551379] INFO : incoming request
    req: {
      "method": "GET",
      "url": "/v3/treatments?authorityName=starts_with(agosti)",
      "hostname": "127.0.0.1:3010",
      "remoteAddress": "127.0.0.1",
      "remotePort": 61045
    }
    reqId: 1
[1601343551394] INFO : request completed
    res: {
      "statusCode": 200
    }
    responseTime: 13.274659991264343
    reqId: 1
```

#### Context

* *node version*: 12.x
* *fastify version*: >=3.4.x
* *os*: Mac

**Comment by mcollina** [comment]
Can you please include a runnable example and not just a snippet? Creating a repo is fine.

**Comment by punkish** [comment]
@mcollina As I was trying to put together a runnable example, I found the problem (created by me). I had some code in `preValidation` hook that was causing the problem. While I don't know what it was causing the problem, removing `preValidation` solved it. Many thanks.

**Comment by mcollina** [comment]
This happens when you call the callback twice, or use both the callback and async in hooks.

**Comment by punkish** [comment]
> This happens when you call the callback twice, or use both the callback and async in hooks.

yes, of course. It is just that I couldn't, for the life of me, figure out where I was making the second call. Anyway, I realized what I was doing was a wrong approach anyway, so I have moved on from that. Many thanks.

**Comment by mcollina** [comment]
```js
// Correct
fastify.addHook('onRequest', (request, reply, done) => {
  // Some code
  done()
})

// Correct
fastify.addHook('onRequest', async (request, reply) => {
  // Some code
})

// Incorrect
fastify.addHook('onRequest', async (request, reply, done) => {
  // Some code
  done()
})
```
