### ISSUE TITLE
Testing with Tap and TypeScript. Stuck at  ESM conflict

### ISSUE THREAD

**Issue by 0x006F** [fastify/help#466]
## 💬 How to write unit ests using `typescript` and `tap`?

I'm entirely new to `Fastify` as the `express` _was_ my de-facto setup while building APIs. So far, I really like this framwork, and getting used to it. So far so good.

Except, when it comes to unit testing, I can't figure out a way to do that. My current project is set with `typescript` with ESM enabled. I was able to execute the `node-tap` test suites (written in ts) without any erros. But when I started to import the `fastify` server instance, it crashed.   (I don't have any `require()` calls in my code)

```json
{
  "level": 50,
  "time": 1623491594383,
  "pid": 69535,
  "hostname": "localhost",
  "code": "ERR_REQUIRE_ESM",
  "stack": "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <redacted>/index.ts\nrequire() of ES modules is not supported.\nrequire() of <redacted>/index.ts from <redacted>/node_modules/ts-node/dist/index.js is an ES module file as it is a .ts file whose nearest parent package.json contains \"type\": \"module\" which defines all .ts files in that package scope as ES modules.\nInstead change the requiring code to use import(), or remove \"type\": \"module\" from <redacted>/package.json.\n\n    at createErrRequireEsm (<redacted>/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:86:15)\n    at assertScriptCanLoadAsCJSImpl (<redacted>/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:19:11)\n    at require.extensions.<computed> (<redacted>/node_modules/ts-node/src/index.ts:1288:5)\n    at Object.<anonymous> (<redacted>/node_modules/append-transform/index.js:64:4)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Module.require (internal/modules/cjs/loader.js:957:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at loadPlugin (<redacted>/node_modules/fastify-autoload/index.js:223:15)\n    at <redacted>/node_modules/fastify-autoload/index.js:34:12",
  "type": "Error",
  "msg": "Must use import to load ES Module: <redacted>/index.ts\nrequire() of ES modules is not supported.\nrequire() of <redacted>/index.ts from <redacted>/node_modules/ts-node/dist/index.js is an ES module file as it is a .ts file whose nearest parent package.json contains \"type\": \"module\" which defines all .ts files in that package scope as ES modules.\nInstead change the requiring code to use import(), or remove \"type\": \"module\" from <redacted>/package.json.\n"
}

```

I was using Jest and supertest prior to this, and that was relatively easy to setup. I didn't see any documentation related to testing (with typescript) in the fastify homepage either. Any help would be appreciated. Thanks!

`tsconfig.json`  

```json  
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```  

`.taprc`  
```
node-arg: [
    --require=ts-node/register,
    --loader=ts-node/esm,
    --experimental-specifier-resolution=node    
]
ts: true
```

## Your Environment

- *node version*: 14.17.0
- *fastify version*: 3.17.0
- *os*: Linux

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by fox1t** [comment]
Hi! Would you mind providing a clonable repository so we can check it out?

**Comment by 0x006F** [comment]
Sure thing. I need to strip down some codes, and will share a clonable one shortly.

**Comment by 0x006F** [comment]
Here the bare repo. https://github.com/0x006F/fastify-esm-tap

**Comment by 0x006F** [comment]
@fox1t looks like this is from `autoloader`. When enabled the `forceESM` to be `true`, it worked!.

**Comment by climba03003** [comment]
Close it as you find the answer yourself.
