### ISSUE TITLE
Fastify-Swagger DTO 

### ISSUE THREAD

**Issue by kamleshkatpara** [fastify/help#532]
Hi,

I am using fastify, i tried the following:

![Screenshot 2021-09-22 120148](https://user-images.githubusercontent.com/16983847/134293989-c169be07-1e14-4d16-8e34-a3a81354239f.png)

![Screenshot 2021-09-22 154827](https://user-images.githubusercontent.com/16983847/134326590-e1df3b33-f2b4-4e66-a304-4037545bb445.png)

![Screenshot 2021-09-22 154909](https://user-images.githubusercontent.com/16983847/134326953-a1db281d-f911-4c1e-aa03-caebf16ff75b.png)

![Screenshot 2021-09-22 154928](https://user-images.githubusercontent.com/16983847/134326996-9b952ee5-b3f6-4779-ba8f-35dabb77792b.png)

I was able to load the schemas in definitions but now paths object changed.

If I try this then I get paths but definitions are gone.

![Screenshot 2021-09-22 155624](https://user-images.githubusercontent.com/16983847/134327535-b2944a8d-0dd3-40c8-a5a3-c5e7a6c47c22.png)

![Screenshot 2021-09-22 155713](https://user-images.githubusercontent.com/16983847/134327678-89359c9a-5739-4255-9447-39b114072df3.png)

I wonder what is missing here @epiphone
 
## 💬  Question here 

a clear , consise and brief decription of your question

```js
// example codes if any
````

If possible add a link to sample codes for error reproduction (github or replit)

## Your Environment

- *node version*: 10, 12, 13
- *fastify version*: >=2.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
I would recommend you to create a minimal, runnable example to reproduce your problem.

**Comment by kamleshkatpara** [comment]
@mcollina Sure, [https://github.com/kamleshkatpara/fastify-typescript](https://github.com/kamleshkatpara/fastify-typescript)

**Comment by Eomm** [comment]
I get an error running `npm run build` on that project. Could you check what is missing in the package json?

> I was able to load the schemas in definitions but now paths object changed.

I see that the schemas are generated by this module: https://www.npmjs.com/package/class-validator-jsonschema
If I have understood correctly, when you move the DTOs files to another directory, the `getSchemas` function returns an empty object?
Is that correct?

**Comment by kamleshkatpara** [comment]
@Eomm Please try with `npm run dev` to run the application. 

I have used this package [https://www.npmjs.com/package/fastify-decorators](https://www.npmjs.com/package/fastify-decorators) for MVC pattern.

When i use the DTO in controllers, then I get the schemas using the getSchemas() function in app.ts.

But it only works if i move the below blow of code at the top of registering the swagger

```javascript
       await app.register(bootstrap, {
                directory: resolve(__dirname, `controllers`),
                mask: /\.controller\./,
            });

        await app.register(require('fastify-swagger'), {
            routePrefix: '/explorer',
            openapi: {
                info: {
                    title: 'Fastify Typescript',
                    description: 'Testing the Fastify swagger API',
                    version: '1.0.0'
                },
                servers: [{ url: `${host}:${port}` }],
                components: {
                    schemas: getSchemas(),
                    securitySchemes: {
                        bearerAuth: {
                            type: 'http',
                            in: 'header',
                            scheme: 'bearer',
                            bearerFormat: 'JWT',
                        },
                    },
                },
            },
            uiConfig: {
                docExpansion: 'full',
                deepLinking: false
            },
            hideUntagged: true,
            exposeRoute: true
        });
```

So this way I am able to get the schemas as below:

[http://localhost:3000/explorer](http://localhost:3000/explorer)

![Screenshot 2021-09-22 154909](https://user-images.githubusercontent.com/16983847/134457966-92b10bec-39aa-4c49-bed5-b339f7b1f72b.png)

![Screenshot 2021-09-22 154928](https://user-images.githubusercontent.com/16983847/134457990-862f4bcf-f239-4234-a03b-d65cb99924f3.png)

But i loose the endpoint paths

If i move the controllers bootstrap block of code below the registering the swagger then I am able to get the endpoint paths but not the schemas (DTOs):

![Screenshot 2021-09-22 155624](https://user-images.githubusercontent.com/16983847/134458164-2caf4b9e-fbf7-4e95-a6f9-079dd3cb3b85.png)

![Screenshot 2021-09-22 155713](https://user-images.githubusercontent.com/16983847/134458170-fba1ef08-002c-4a38-8287-143e666a27c7.png)

Hope I was able to explain it.

**Comment by Eomm** [comment]
mmmm could you remove all the unnecessary stuff?

It does not start with the `docker-compose up` command

> server    | > cross-env NODE_ENV=development && ts-node-dev --cls src/app.ts
server    |
server    | [INFO] 16:49:46 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.3)
server    |
[1632502188083] ERROR (33 on 59a9d50a2b70): connect ECONNREFUSED 127.0.0.1:3306
server    |     Error: connect ECONNREFUSED 127.0.0.1:3306
server    |         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
server    |         --------------------
server    |         at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
server    |         at Protocol.handshake (/app/node_modules/mysql/lib/protocol/

**Comment by kamleshkatpara** [comment]
@Eomm As I have mentioned above please run the application using `npm run dev` command.

**Comment by Eomm** [comment]
But it won't start without the whole system (mysql).

Should I configure it by myself?

**Comment by kamleshkatpara** [comment]
Yes

**Comment by zekth** [comment]
Please: 
> Create a minimal, runnable example to reproduce your problem

This is not the case.

**Comment by simoneb** [comment]
@kamleshkatpara did you solve this issue?

**Comment by L2jLiga** [comment]
Hi @simoneb, it seems like issue finally were resolve,

You can check this issue for more info https://github.com/L2jLiga/fastify-decorators/issues/565

**Comment by kamleshkatpara** [comment]
@simoneb Yes, I did it was more into fastify-decorators package.
