### ISSUE TITLE
please Help Me to solve this issue 

### ISSUE THREAD

**Issue by Amineaamer** [fastify/help#535]
#### You have already researched for similar issues?

yes but i don't know where is the issue in my code 
 

```ts
import { Server, IncomingMessage, ServerResponse } from "http";
import { FastifyInstance } from "fastify";
import { FastifyServer } from "../servicestore";
import { IUser, IUserAUTHRequest, IUserRequest } from "../interfaces";
export const UserController = (
    fastify: FastifyInstance<Server, IncomingMessage, ServerResponse>,
    options: any,
    done: () => void
): void => {
    FastifyServer.server.after(() => {
        FastifyServer.server.addHook("onRequest", (req, res, rdy) => {
            const valid = FastifyServer.authenticate(req);
            if (!valid) {
                void res.send(new Error("Du bist nicht würdig"));
            } else {
                rdy();
            }
        });
        // User anlegen
        FastifyServer.server.post<IUserRequest>("/user/create", async (request, response) => {
            try {
                const user = (request.body as unknown) as IUser;
                const existingUser = await FastifyServer.userModel.findOne({ username: user.username });
                if (!existingUser) {
                    if (user.admin === undefined || null) {
                        user.admin = false;
                        user.changePW = true;
                    }
                    user.password = FastifyServer.getPasswordHash("bitteAEndern");
                    const newUserDoc = await FastifyServer.userModel.create(user);
                    const res = {
                        userID: newUserDoc.get("_id"),
                        username: newUserDoc.get("username"),
                        admin: newUserDoc.get("admin"),
                        changePW: newUserDoc.get("changePW"),
                    };
                    void response.send(res);
                } else {
                    void response.send(new Error("User already exists!"));
                }
            } catch (error) {
                void response.send(error);
            }
        });
        // User authentifizieren
        FastifyServer.server.post<IUserAUTHRequest>("/user/auth", async (request, response) => {
            try {
                console.log(request.body);
                const username = request.body.username;
                const password = request.body.password;
                const user = await FastifyServer.userModel.findOne({ username });
                if (!user) {
                    throw new Error("This User doesnt exist!");
                } else if (!FastifyServer.checkPassword(password, user.get("password"))) {
                    throw new Error("Wrong Password!");
                } else {
                    const res = {
                        userID: user._id.toString(),
                        username: user.get("username"),
                        admin: user.get("admin"),
                        changePW: user.get("changePW"),
                    };
                    console.log(res);
                    void response.send(res);
                }
            } catch (error) {
                void response.send(error);
            }
        });
        // User ändern
        FastifyServer.server.patch<IUserRequest>("/user/update", async (request, response) => {
            try {
                const userUpdate = request.body.user;
                const user = await FastifyServer.userModel.findOne({ username: userUpdate.username });
                if (!FastifyServer.checkPassword(userUpdate.password!, user!.get("password"))) {
                    userUpdate.changePW = false;
                    userUpdate.password = FastifyServer.getPasswordHash(userUpdate.password!);
                    await user!.update(userUpdate);
                    const updatedUser = await FastifyServer.userModel.findOne({ username: userUpdate.username });
                    const res = {
                        userID: updatedUser!.get("_id"),
                        username: updatedUser!.get("username"),
                        admin: updatedUser!.get("admin"),
                        changePW: updatedUser!.get("changePW"),
                    };
                    void response.send(res);
                } else {
                    void response.send(new Error("You cant use the same password!"));
                }
            } catch (error) {
                void response.send(error);
            }
        });
        // User löschen
        FastifyServer.server.delete<IUserRequest>("/user/delete", async (request, response) => {
            try {
                const user = request.body.user;
                const deletedUser = await FastifyServer.userModel.findOneAndDelete({ username: user.username });
                void response.send(deletedUser);
            } catch (error) {
                void response.send(error);
            }
        });
    });
    done();
};

//serviceStore.ts

import { IncomingMessage, Server, ServerResponse } from "http";
import fastify, { FastifyInstance, FastifyRequest } from "fastify";
import { Model, Mongoose, Schema } from "mongoose";
import { RouteGenericInterface } from "fastify/types/route";
import { IAuth } from "./interfaces";
class ServerClass {
    public server: FastifyInstance<Server, IncomingMessage, ServerResponse>;
    public articleModel: Model<unknown, unknown, unknown>;
    public userModel: Model<unknown, unknown, unknown>;
    private bycript = require("bcrypt");
    private saltRounds = 12;
    private auth = require("basic-auth");
    private mongoose = new Mongoose();
    private articleSchema: Schema = new Schema(
        {
            name: { type: String, required: true },
            price: { type: Number, required: true },
            description: { type: String },
        },
        {
            collection: "Artikel",
            versionKey: false,
        }
    );
    private userSchema: Schema = new Schema(
        {
            username: { type: String, required: true },
            password: { type: String, required: true },
            admin: { type: Boolean },
            changePW: { type: Boolean },
        },
        {
            collection: "User",
            versionKey: false,
        }
    );
    constructor() {
        this.server = fastify({ logger: true });
        void this.connectDB();
        this.articleModel = this.mongoose.model("Artikel", this.articleSchema);
        this.userModel = this.mongoose.model("User", this.userSchema);
    }
    private connectDB = async (): Promise<void> => {
        await this.mongoose
            .connect("mongodb://localhost:27017/Artikelverwaltung", { serverSelectionTimeoutMS: 15000 })
            .catch(err => console.log(err.reason));
    };
    public authenticate = (request: any): boolean => {
        if (request.url === "/health") {
            return true;
        }
        const userLoginData: IAuth = this.auth(request);
        let valid = false;
        if (userLoginData) {
            valid = true;
            valid = userLoginData.name === "GatewayService" && valid;
            valid = userLoginData.pass === "superSicheresUndAufKeinenFallSchlechtesPasswort" && valid;
        }
        return valid;
    };
    public getPasswordHash = (password: string): string => {
        const salt = this.bycript.genSaltSync(this.saltRounds);
        return this.bycript.hashSync(password, salt);
    };
    public checkPassword = (password: string, hash: string): boolean => this.bycript.compareSync(password, hash);
}
export const FastifyServer = new ServerClass();


```

#### What was the result you received?
{"level":30,"time":1632833456178,"pid":29391,"hostname":"hannes-Latitude-E7450","reqId":"req-1","res":{"statusCode":400},"err":{"type":"FastifyError","message":"Request body size did not match Content-Length","stack":"FastifyError: Request body size did not match Content-Length\n    at IncomingMessage.onEnd (/home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/node_modules/fastify/lib/contentTypeParser.js:235:18)\n    at IncomingMessage.emit (events.js:228:7)\n    at IncomingMessage.EventEmitter.emit (domain.js:475:20)\n    at endReadableNT (_stream_readable.js:1185:12)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","name":"FastifyError","code":"FST_ERR_CTP_INVALID_CONTENT_LENGTH","statusCode":400},"msg":"Request body size did not match Content-Length"}
{"level":30,"time":1632833456185,"pid":29391,"hostname":"hannes-Latitude-E7450","reqId":"req-1","res":{"statusCode":400},"responseTime":15.15276899933815,"msg":"request completed"}
{"level":40,"time":1632833456487,"pid":29391,"hostname":"hannes-Latitude-E7450","reqId":"req-1","err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (/home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/node_modules/fastify/lib/reply.js:123:26)\n    at /home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/src/routes/user.controller.ts:123:39\n    at step (/home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/src/routes/user.controller.ts:33:23)\n    at Object.next (/home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/src/routes/user.controller.ts:14:53)\n    at fulfilled (/home/hannes/Documents/artikelverwaltung/artikelverwaltungbackend/src/routes/user.controller.ts:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
#### Context

* *node version*: 4,5,6,7,8,9
* *fastify version*: >=0.37.0
* *ubuntu*:
* *any other relevant information*:

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

**Comment by mcollina** [comment]
> Request body size did not match Content-Length

This means that you are sending an HTTP POST with a Content-Length that does not match the actual length of the sent data. This is an HTTP spec violation. There is nothing wrong in your code, you need to adjust your client.
