### ISSUE TITLE
I cannot fulfil the promise in my fastify typescript setup

### ISSUE THREAD

**Issue by waqastanoli** [fastify/help#650]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

#### What are you trying to achieve, or the steps to reproduce?

when i use await in the beginning of a handler it throws `FST_ERR_PROMISE_NOT_FULFILLED`, it does not break the application and the data is inserted in database and i get a response, but still in command line, it keep throwing this error. If i use a callback .then() and nest the whole code inside the error is gone, which i want to avoid to avoid callback hell, when the code increases.

app.ts
```js
import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from 'fastify-autoload';
import { FastifyPluginAsync } from 'fastify';

export type AppOptions = {
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>;

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
  // Place here your custom code!

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })
 
  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

};

export default app;
export { app }

```
/routes/v1/channels/index.ts
```js
import { FastifyPluginAsync } from "fastify"
import controller from '../../../controllers/channelsController'
const index: FastifyPluginAsync = async (fastify, opts): Promise<void> => {
  
    
  fastify.post('/', (request:any,  reply:any) => controller.create(request,fastify, reply))
  fastify.get('/:id', (request:any, reply:any) => controller.retrieve(request,fastify, reply))
  fastify.put('/:id', (request:any, reply:any) => controller.update(request,fastify, reply))
  fastify.delete('/:id', (request:any, reply:any) => controller.delete(request,fastify, reply))
  fastify.post('/list', (request:any,  reply:any) => controller.list(request,fastify, reply))

  

}

export default index;

```
controllers/channelsController.ts

```js

import Channels from '../models/channels'
import Responses from '../utils/responses';
import UserRoles from '../models/userRoles'
import {VENDOR_ID, PRESENTER_ID} from '../config/constants'
class usersController {
    
   
    constructor() {
      
    }
    async create(request:any, fastify:any, reply:any){                       
         
        
        const request_body = request.body;
        if(request_body.vendor_id){
            const is_vendor = await UserRoles.findOne({where:{
                user_id:request_body.vendor_id,
                role_id:VENDOR_ID
            }})
            if(is_vendor==null){
                Responses.failed(undefined, 'User is not a vendor',"vendor_id", 401, reply)
                return;
            }
        }
        if(request_body.presenter_id){
            const is_vendor = await UserRoles.findOne({where:{
                user_id:request_body.presenter_id,
                role_id:PRESENTER_ID
            }})
            if(is_vendor==null){
                Responses.failed(undefined, 'User is not a presenter',"presenter_id", 401, reply)
                return;
            }
        }
        Channels.create(request_body)
        .then(async (result) => {
            
            const inserted = await Channels.findByPk(result.get({ plain: true }).id, {
                include: ["presenter","vendor"]
            })            
            
            Responses.created(inserted, reply)
            return;        
        })
        .catch((err) => {     
            console.log(err)                  
            Responses.errors(err,reply);
            return
        });
        
    }
    retrieve(request:any, fastify:any, reply:any){        
        
        if (isNaN(request.params.id) == true) {
            Responses.notFound(reply);
            return;
        }
        
        Channels.findByPk(request.params.id, {
            include: ["presenter","vendor"]
        })
        .then(data => {
            if(!data) {
                Responses.notFound(reply);       
                return                          
            }
            Responses.retrieved(data, reply);   
            return
          })
        .catch((err) => {            
            Responses.errors(err, reply );
            return;
        });
    }
    async update(request:any, fastify:any, reply:any){        
        const id = request.params.id;
        if (isNaN(id) == true) {
            Responses.notFound(reply);       
            return
        }
        

        const job = await Channels.findOne({where: {id:  id}});
        if (!job) {
            Responses.notFound(reply);       
            return
        }
        
        
        for(let key in request.body){
            job!.set(key,request.body[key]);
        }
        await job!.save();
        const role = await Channels.findByPk(id, {
            include: ["presenter","vendor"]
        })  
        Responses.updated(role, reply);        
        return;


        
    }
    delete(request:any, fastify:any, reply:any){
        const id = request.params.id;
        if (isNaN(id) == true) {
            Responses.notFound(reply);       
            return
        }
        
        Channels.destroy({
            where: {
               id: request.params.id 
            }
         }).then(function(rowDeleted){ 
            if(rowDeleted === 1){
                Responses.deleted(true, reply)                
                return;
            } else {
                Responses.deleted(false, reply)                
                return;
            }
         }, function(err){
            Responses.errors(err, reply );
            return;
         });
    }
    
    list(request:any, fastify:any, reply:any){   
        
        
       var where_dynamic = <any>[];
       if(typeof request.body.status!=="undefined"){                
            where_dynamic.push({'status' : request.body.status});        
       }   
       const options = {
          offset:(isNaN(request.body.offset)==false)?request.body.offset:0,
          limit: (isNaN(request.body.limit)==false)?request.body.limit:10,
          where: <any>where_dynamic
       };
       
       
       
       Channels.findAndCountAll(options)
       .then((result) => {           
        Responses.list(result, options, reply);
        return;
       })
       .catch((err) => {           
            Responses.errors(err, reply );
            return;
       });
       
   }
   
    
}
const controller = new usersController();
export default controller;
```

#### What was the result you received?
Although there is no blocking error, the transactions work fine but in the create method which is async and when i used await in the beginning it throws this errors, which does not affect but it says its an error.
```
FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
[App]     at C:\workspace\\api\node_modules\fastify\lib\wrapThenable.js:30:30
[App]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[App] {
[App]   "err": {
[App]     "type": "FastifyError",
[App]     "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
[App]     "stack": "FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\workspace\\\\api\\node_modules\\fastify\\lib\\wrapThenable.js:30:30\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
[App]     "name": "FastifyError",
[App]     "code": "FST_ERR_PROMISE_NOT_FULFILLED",
[App]     "statusCode": 500
[App]   }
[App] }
```

#### What did you expect?
a clean CLI with request logs not this error
#### Context

* *node version*: 16.14
* *fastify version*: ^3.0.0
* *os*:  Windows 10
* *using sequelize ORM and mysql db*

**Comment by climba03003** [comment]
1. Do not use `async-await` with `Promise.then`.
2. If you want to terminate the executation, do not just `return`. It pass `undefined` to `fastify`. Use `return reply` instead.

**Comment by waqastanoli** [comment]
for any one else facing the same issue, here is a way around
```js
async create(request:any, fastify:any, reply:any){                       
         try {
            const request_body = request.body;
            if(request_body.vendor_id){
                const is_vendor = await UserRoles.findOne({where:{
                    user_id:request_body.vendor_id,
                    role_id:VENDOR_ID
                }})
                if(is_vendor==null){
                    Responses.failed(undefined, 'User is not a vendor',"vendor_id", 401, reply)
                    return;
                }
            }
            if(request_body.presenter_id){
                const is_vendor = await UserRoles.findOne({where:{
                    user_id:request_body.presenter_id,
                    role_id:PRESENTER_ID
                }})
                if(is_vendor==null){
                    Responses.failed(undefined, 'User is not a presenter',"presenter_id", 401, reply)
                    return;
                }
            }
            const result = await <any>Channels.create(request_body);
            const inserted = await Channels.findByPk(result.get({ plain: true }).id, {
                include: ["presenter","vendor"]
            })            
            
            Responses.created(inserted, reply)
            return;            
         } catch (error) {
             Responses.errors(error,reply);        
             return;     
         }                        
    }
```
