### ISSUE TITLE
How to handle stream errors passed to reply.raw?

### ISSUE THREAD

**Issue by budarin** [fastify/help#749]
## 💬  Question here 

Try to use React SSR

```js
    const App = () => {
      throw new Error('some error in React App');
    };
```    
set Errorhanler

```js
fastifyInstance.setErrorHandler(async function (error, req, res) {
  .....
}
```
and register the route

```js 
    fastify.route({
        url: '/',
        method: 'GET',
        handler: async (req, reply) => {
            let didError = false;

            res.raw.writeHead(HTTP_OK_CODE, { 'Content-Type': 'text/html; charset=utf-8' });

            const stream = renderToPipeableStream(<App />, {
                onShellReady: async () => {
                    if (didError) {
                        res.raw.statusCode = HTTP_SERVER_ERROR_CODE;
                        res.raw.end(HttpErrorMessages[HTTP_SERVER_ERROR_CODE]);
                    } else {
                        res.raw.write('<!doctype html><html><head>');
                        res.raw.write(`<meta property="version" content="${APP_VERSION}">`);
                        res.raw.write('</head><body>');
                        stream.pipe(res.raw);
                        res.raw.end('</body></html>');
                    }
                },
                onShellError: (error) => {
                    didError = true;
                    req.log.error({ error, where: 'onShellError' });

                    res.raw.statusCode = HTTP_SERVER_ERROR_CODE;
                    res.raw.end('Error !!');
                },
                onError: async (error) => {
                    didError = true;
                    req.log.error({ error, where: 'onError' });
                },
            });
        }
    });
````

When try to render the App get the uncaughtException instead of being intercepted by the application handler (so the service is shutting down due to this error):
```
"Error: onError returned something with a type other than \"string\". onError should return a string and may return null or undefined but must not return anything else. It received something of type \"object\" instead
at Y (webpack://web-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:69:70)
at Qc (webpack://web-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:88:311)
at Immediate.<anonymous> (webpack://web-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:98:56)
at process.processImmediate (node:internal/timers:471:21)"
```

How to intercept such errors by the fastify application?

## Your Environment

- *node version*: 18
- *fastify version*: 4.5.3
- *os*: Mac, Windows
- React 18

**Comment by mcollina** [comment]
As a quick help: you are misusing async and promises. You should add `return reply` at the end of your route and possibly call `reply.hjack()`.

**Comment by budarin** [comment]
@mcollina 

Thanks!
returning reply at the end of the route helped to move setting `content-type` into the function

I didn't quite understand about async and Promise - I looked at the description of the types - it seems that all the calls to reply.raw are synchronous.

Did you mean the documentation section "[Async-Await and Promises](https://www.fastify.io/docs/latest/Reference/Reply/#async-await-and-promises)"?

**Comment by budarin** [comment]
The main problem remains - if an error occurs in the component, the service crashes with an uncaught Exception

**Comment by kibertoad** [comment]
@budarin You should not mix callbacks (e. g. in event handlers) and promises.
https://www.youtube.com/watch?v=XV-u_Ow47s0 is an essential viewing for any Node.js developer

**Comment by budarin** [comment]
@kibertoad 

Thanks! will watch.
