### ISSUE TITLE
Fastify session - [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by LuisBarroso37** [fastify/help#788]
fastify v4.9.2
@fastify/session v10.0.2
Node.js v18.12

I am always getting an error ERR_HTTP_HEADERS_SENT after sending back a response to the frontend. The error seems to be coming from @fastify/session as you can see from the stack trace:
I am using mongo db to store sessions with the **connect-mongo** package.

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.writeHead (node:_http_server:377:21)
    at onSendEnd (C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\fastify\lib\reply.js:598:7)
    at wrapOnSendEnd (C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\fastify\lib\reply.js:537:5)
    at next (C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\fastify\lib\hooks.js:213:7)
    at C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\@fastify\session\lib\fastifySession.js:190:9
    at C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\@fastify\session\lib\session.js:171:9
    at C:\Users\LuísBarroso\Desktop\Rootit\Rootit-server\node_modules\connect-mongo\src\lib\MongoStore.ts:399:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
```

Has anyone had the same issue?

This is my app.ts

```
// Get environmental variables
import * as dotenv from 'dotenv';
dotenv.config();

import fastify from 'fastify';
import { fastifyCookie } from '@fastify/cookie';
import fastifySession from '@fastify/session';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import swagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import MongoStore from 'connect-mongo';
import fs from 'fs';
import mongoose from 'mongoose';

import { config } from './configuration/config';
import { usersRouter } from './controllers/users/users.router';
import {
  failedValidationResponse,
  internalServerErrorResponse,
} from './utils/errors';
import { usersConnection } from './mongo-connection';
import {
  errorResponseSchema,
  successResponseSchema,
} from './schemas/response.schemas';
import type { UserRoles } from './models/user';
import { authRouter } from './controllers/auth/auth.router';

function main() {
  // Check that all required environmental variables are defined
  const requiredEnvVariables = [
    'SESSION_SECRET',
    'FRONTEND_URL',
    'COSMOSDB_BASE_URL',
    'COSMOSDB_OPTIONS',
  ];
  requiredEnvVariables.forEach((key) => {
    if (!process.env[key]) {
      throw new Error(key + ' must be defined');
    }
  });

  const server = fastify({
    https: {
      key: fs.readFileSync('...'),
      cert: fs.readFileSync('...'),
    },
    logger: config.logger,
  });

  // Middlewares
  server.register(cors, {
    origin: config.server.frontendUrl,
    methods: ['GET', 'PUT', 'POST', 'DELETE'],
    allowedHeaders: ['Content-Type', 'Authorization'],
    credentials: true,
  });
  server.register(swagger, {
    mode: 'dynamic',
    openapi: {
      ...
  });
  server.register(fastifySwaggerUi, {
    routePrefix: '/documentation',
    initOAuth: {},
    uiConfig: {
      docExpansion: 'full',
      deepLinking: false,
    },
    uiHooks: {
      onRequest: function (_req, _reply, next) {
        next();
      },
      preHandler: function (_req, _reply, next) {
        next();
      },
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
  });
  server.register(helmet, (instance) => {
    return {
      contentSecurityPolicy: {
        directives: {
          ...helmet.contentSecurityPolicy.getDefaultDirectives(),
          'form-action': ["'self'"],
          'img-src': ["'self'", 'data:', 'validator.swagger.io'],
          'script-src': ["'self'"].concat(instance.swaggerCSP.script),
          'style-src': ["'self'", 'https:'].concat(instance.swaggerCSP.style),
        },
      },
    };
  });
  server.register(fastifyCookie);
  server.register(fastifySession, {
    secret: config.sessionSecret,
    saveUninitialized: false,
    cookie: {
      maxAge: 24 * 60 * 60 * 1000,
      sameSite: 'none',
      secure: true,
      httpOnly: true,
    },
    store: MongoStore.create({
      client: usersConnection.getClient(),
      dbName: 'users',
      collectionName: 'sessions',
      stringify: false,
      autoRemove: 'interval',
      autoRemoveInterval: 10,
    }),
  });

  // Shared JSON schemas
  server.addSchema(errorResponseSchema);
  server.addSchema(successResponseSchema);

  // Routes
  server.register(usersRouter, { prefix: '/api/users' });
  server.register(authRouter, { prefix: '/api/auth' });

  // Close all mongoDB connections when server shuts down
  server.addHook('onClose', async () => {
    for (let conn of mongoose.connections) {
      await conn.close();
    }
  });

  // Set fastify's error handler to catch unknown and validation errors
  server.setErrorHandler(function (error, req, reply) {
    if (error.validation) {
      return failedValidationResponse(req, reply, error.validation);
    }

    return internalServerErrorResponse(req, reply, error);
  });

  // Start running server
  server.listen({ port: config.server.port }, (err, address) => {
    if (err) {
      server.log.error(err);
      process.exit(1);
    }

    server.log.info(`Server listening at ${address}`);
  });
}

main();
```

Prehandler function:

```
import type {
  FastifyReply,
  FastifyRequest,
  HookHandlerDoneFunction,
} from 'fastify';

import { authenticationRequiredResponse } from '../utils/errors';

export async function requireAuth(
  req: FastifyRequest,
  reply: FastifyReply,
  done: HookHandlerDoneFunction
) {
  if (!req.session.user) {
    return authenticationRequiredResponse(req, reply);
  }

  done();
}

```

This is the route where I have issues:

```server.get(
    '/me',
    { schema: meSchema, preHandler: [requireAuth] },
    async function (req, reply) {
      if (!req.session.user) {
        return internalServerErrorResponse(
          req,
          reply,
          'Could not find user session'
        );
      }

      return reply.status(200).send({ user: req.session.user });
    }
  );
```

My errors are all sent like this:

```
export function authenticationRequiredResponse(
  _req: FastifyRequest,
  res: FastifyReply
) {
  res.status(401).send({
    message: 'You must be authenticated to access this resource',
  });
}
```

**Comment by climba03003** [comment]
You prehandler is mixing `async-await` and `callback`. Use either one.

And no `middleware`.

**Comment by LuisBarroso37** [comment]
Thanks @climba03003! Removing async from the function, fixed the issue.
