### ISSUE TITLE
Problem ex-exporting module

### ISSUE THREAD

**Issue by clluiz** [fastify/help#816]
#### You have already researched for similar issues?

Yes.

#### What are you trying to achieve, or the steps to reproduce?

My project has the following structure:

- src
    - plugins
        - scheduling.ts
   - scheduling
       - routes.ts

My scheduling/routes.ts file:

`
import { KairosInstance } from "../kairosInstance"

export default async function (app : KairosInstance) {
  app.get('/scheduling', async () => {
    return []
  })
}
`

I want to re-export this function in my routes/scheduling.ts:

`
import { default as SchedulingRoutes } from '../scheduling/routes'

export default SchedulingRoutes
`

And my main file:

`
export async function main (options: any) {
  const app = fastify()
  app.register(autoload, {
    dir: join(import.meta.url, './routes'),
    options
  })
  return app
}
`

#### What was the result you received?

My application don't start and I get the following error:

AvvioError [Error]: Plugin must be a function or a promise. Received: 'object'
    at assertPlugin (/home/cleiton/projetos/kairos/backend2/node_modules/avvio/boot.js:207:11)
    at Boot._addPlugin (/home/cleiton/projetos/kairos/backend2/node_modules/avvio/boot.js:240:12)
    at Boot.use (/home/cleiton/projetos/kairos/backend2/node_modules/avvio/boot.js:216:25)
    at Object.server.<computed> [as register] (/home/cleiton/projetos/kairos/backend2/node_modules/avvio/boot.js:40:14)
    at registerPlugin (/home/cleiton/projetos/kairos/backend2/node_modules/@fastify/autoload/index.js:327:11)
    at registerAllPlugins (/home/cleiton/projetos/kairos/backend2/node_modules/@fastify/autoload/index.js:111:19)
    at autoload (/home/cleiton/projetos/kairos/backend2/node_modules/@fastify/autoload/index.js:91:7) {
  code: 'AVV_ERR_PLUGIN_NOT_VALID'
}

#### What did you expect?

I expect that the application start's and the route /scheduling to be available

#### Context

* *node version*: 18.8.0
* *fastify version*: >=4.10.2
* *os*: Ubuntu

**Comment by clluiz** [comment]
Solved. This problem was caused by another problem in my code.
