### ISSUE TITLE
Typescript support for fastify-auth plugin #2

### ISSUE THREAD

**Issue by flipperlite** [fastify/help#827]
I have the same problem as [this closed issue](https://github.com/fastify/help/issues/818). It references other Typescript issues too.

My `package.json` versions:

fastify ^4.12.0
fastify-plugin ^4.5.0
@fastify/auth ^4.2.0 (fastify-auth is not installed)
node v16.13.0
typescript ^4.9.5
ts-node ^10.9.1

My tsconfig.ts file has the following:

```javascript
"compilerOptions": {
    "esModuleInterop": true,
}
```

When run like this per the README.md file:

```javascript
fastify
    .register(require('@fastify/auth'))
```

I get the VS Code compile error:

`
Property 'auth' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>'.ts(2339)
`

I changed to the following code to resolve the VS Code compile error:

```javascript
import fastifyAuth from '@fastify/auth'
import Fastify, { FastifyReply, FastifyRequest, HookHandlerDoneFunction } from 'fastify'
const fastify = Fastify({
    logger: true
})

fastify
    .register(fastifyAuth)
    .route({
        method: 'GET',
        url: '/',
        preHandler: fastify.auth([
        (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 1'); done() },
        (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 2'); done() },
        (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 3'); done(new Error('you are not authenticated')) },
        (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 4'); done() },
        (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 5'); done(new Error('you shall not pass')) }
        ], { run: 'all' }),
        handler: (req, reply) => { reply.send({ hello: 'world' }) }
    })

/**
 * Run the server!
 */
const start = async () => {
    try {
        await fastify.listen({ port: 3000 })
    } catch (err) {
        fastify.log.error(err)
        process.exit(1)
    }
}
start()
```

With the previous code, I get no errors in VS Code but when trying to run the server i get the error:

```bash
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/index-simple.ts`
/Users/username/Dev/my-repo/src/index-simple.ts:12
        preHandler: fastify.auth([
                            ^
TypeError: fastify.auth is not a function
    at Object.<anonymous> (/Users/username/Dev/my-repo/src/index-simple.ts:12:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/Users/username/Dev/my-repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/username/Dev/my-repo/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/Users/username/Dev/my-repo/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/Users/username/Dev/my-repo/node_modules/ts-node/src/bin.ts:95:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Asjas** [comment]
That is not a TypeScript error. You need to `await` the registration of the plugin.

```js
await fastify.register(fastifyAuth);

fastify.route({
    method: 'GET',
    url: '/',
    preHandler: fastify.auth([
    (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 1'); done() },
    (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 2'); done() },
    (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 3'); done(new Error('you are not authenticated')) },
    (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 4'); done() },
    (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 5'); done(new Error('you shall not pass')) }
    ], { run: 'all' }),
    handler: (req, reply) => { reply.send({ hello: 'world' }) }
})
```

Then add your routes. Route registration is sync and you need to await any plugins before it if it depends on that plugin.

https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#synchronous-route-definitions-2954

**Comment by flipperlite** [comment]
Thanks. I completely missed the `.after()` method call in the [README.md](https://github.com/fastify/fastify-auth) file. Hopefully this updated code can help out the next person who runs into this problem getting it to run in Typescript. Put the following code into your `index.ts` file and run `npx nodemon ./index.ts --exec ts-node` with nodemon or `npx ts-node ./index.ts` without nodemon. You can also put the commands into your `package.json` npm run scripts.

Dependencies:
```
npm i nodemon ts-node --save-dev
npm i fastify @fastify/auth --save
```

Code:

```javascript
import fastifyAuth from '@fastify/auth'
import Fastify, { FastifyReply, FastifyRequest, HookHandlerDoneFunction } from 'fastify'
const fastify = Fastify({
    logger: true
})

/**
 * Run the server!
 */
const start = async () => {
    try {
        await fastify.register(fastifyAuth)
        fastify
            .route({
                method: 'GET',
                url: '/',
                preHandler: fastify.auth([
                (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 1'); done() },
                (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 2'); done() },
                (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 3'); done(new Error('you are not authenticated')) },
                (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 4'); done() },
                (request: FastifyRequest, reply: FastifyReply,  done: HookHandlerDoneFunction) => { console.log('executed 5'); done(new Error('you shall not pass')) }
                ], { run: 'all' }),
                handler: (req, reply) => { reply.send({ hello: 'world' }) }
            })
        await fastify.listen({ port: 3000 })
    } catch (err) {
        fastify.log.error(err)
        process.exit(1)
    }
}
start()
```
