### ISSUE TITLE
Help: @fastify/rate-limit | Rate limiter not working [FOR ME] & default headers not included

### ISSUE THREAD

**Issue by HardCodeProgrammer** [fastify/help#832]
I'm a beginner, so pls bear with me. 🙏

## My Code
```js
// Import Fastify ------- 
const fastify = require("fastify")({
	logger: {
		level: "info",
		serializers: { .  .  . }, // custom some serializers
		file: "server.log",
	},
});

// Rate Limiter ------------------------------------------------------
fastify.register(require("@fastify/rate-limit"), {
	max: 3,
	timeWindow: 30000,
});

// Add header
fastify.addHook("preHandler", (req, res, done) => {
	res.header("accept-encoding", "br");
	done();
});

// There are many routes but for this issue i will take this simple one
// Uptime Monitor
fastify.get("/monitor", async (req, res) => {
	res.send("monitor");
});

// Later in my code
// -------------------------------------------------------------------------------------------------------------
// Run the server!
// -----------------------------------------------------------------------------------------------------------
const start = async () => {
	try {
		await fastify.listen({ port: PORT });
		console.log("Server started in port " + PORT);
	} catch (err) {
		fastify.log.error(err);
		process.exit(1);
	}
};

start();

```
## Expected result 
The following default headers in my response 
| Header | Description |
|--------|-------------|
|`x-ratelimit-limit`     | how many requests the client can make
|`x-ratelimit-remaining` | how many requests remain to the client in the timewindow
|`x-ratelimit-reset`     | how many seconds must pass before the rate limit resets
|`retry-after`           | if the max has been reached, the milliseconds the client must wait before they can make new requests

as mentioned in the README.md [here ↗](https://github.com/fastify/fastify-rate-limit/blob/master/README.md#:~:text=addHeadersOnExceeding%3A%20%7B%20//%20default%20show%20all%20the%20response%20headers%20when%20rate%20limit%20is%20not%20reached%0A%20%20%20%20%27x%2Dratelimit%2Dlimit%27%3A%20true%2C%0A%20%20%20%20%27x%2Dratelimit%2Dremaining%27%3A%20true%2C%0A%20%20%20%20%27x%2Dratelimit%2Dreset%27%3A%20true%0A%20%20%7D%2C)

## Actual Result
![image](https://user-images.githubusercontent.com/75080162/217207918-d3d5c051-576f-4ab4-9599-8db4d1b05ef7.png)

After exceeding the limits the server should return a `HTTP 429`. But that does not work either :(

## Other Dependencies used
*package.json*
```json
{
  "name": "myproj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.js"
  },
  "keywords": [],
  "author": "HardCodeProgrammer",
  "license": "ISC",
  "dependencies": {
    "@fastify/cors": "^8.2.0",
    "@fastify/postgres": "^5.2.0",
    "@fastify/rate-limit": "^7.6.0",
    "@fastify/websocket": "^7.1.2",
    "fastify": "^4.12.0",
    "pg": "^8.9.0",
    "uuid": "^9.0.0",
    "ws": "^8.12.0"
  },
  "devDependencies": {
    "nodemon": "^2.0.20"
  }
}
```
## Production/Development Environment

- *node version*: 18.13.0
- *fastify version*: 4.12.0
- *os*: 
     - **Development**: Windows
     -  **Production**: Ubuntu Linux
- *Web server*: Apache 

Any additional information can be provided. 
Please help

**Comment by Fdawgs** [comment]
You need to await it when registering it, as documented here:

https://github.com/fastify/fastify-rate-limit#usage

**Comment by HardCodeProgrammer** [comment]
I tried that but.. since it's called in the top level and not inside some async function, I get this error..

Thanks for replying.. any other solutions please :( 🙏
```bash
await fastify.register(require("@fastify/rate-limit"), {
^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.13.0
```

**Comment by Uzlopak** [comment]
Well wrap the calls in a async function and await them

```js
async function createServer () {

// Import Fastify ------- 
const fastify = require("fastify")({
	logger: {
		level: "info",
		serializers: { .  .  . }, // custom some serializers
		file: "server.log",
	},
});

// Rate Limiter ------------------------------------------------------
await fastify.register(require("@fastify/rate-limit"), {
	max: 3,
	timeWindow: 30000,
});

// Add header
fastify.addHook("preHandler", (req, res, done) => {
	res.header("accept-encoding", "br");
	done();
});

// There are many routes but for this issue i will take this simple one
// Uptime Monitor
fastify.get("/monitor", async (req, res) => {
	res.send("monitor");
});
}

// Later in my code
// -------------------------------------------------------------------------------------------------------------
// Run the server!
// -----------------------------------------------------------------------------------------------------------
const start = async () => {
	try {
		await createServer().listen({ port: PORT });
		console.log("Server started in port " + PORT);
	} catch (err) {
		fastify.log.error(err);
		process.exit(1);
	}
};

start();
```

**Comment by HardCodeProgrammer** [comment]
> Well wrap the calls in a async function and await them

```
TypeError: createServer(...).listen is not a function
    at start E:\Projects\my_project\index.js:551:24)
    at Object.<anonymous> (E:\Projects\my_project\index.js:559:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
E:\Projects\my_project\node_modules\sonic-boom\index.js:359
    throw new Error('sonic boom is not ready yet')
          ^

Error: sonic boom is not ready yet
    at SonicBoom.flushSync (E:\Projects\my_project\node_modules\sonic-boom\index.js:359:11)
    at autoEnd (E:\Projects\my_project\node_modules\pino\lib\tools.js:267:12)
    at callRefs (E:\Projects\my_project\node_modules\on-exit-leak-free\index.js:45:7)
    at process.onExit (E:\Projects\my_project\node_modules\on-exit-leak-free\index.js:29:3)
    at process.emit (node:events:513:28)
    at process.exit (node:internal/process/per_thread:190:15)
    at start E:\Projects\my_project\index.js:555:11)
    at Object.<anonymous> (E:\Projects\my_project\index.js:559:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
```

**Comment by Uzlopak** [comment]
yeah, createServer is missing a `return fastify`

**Comment by HardCodeProgrammer** [comment]
Thanks it worked
